# Generated by Django 2.2.5 on 2021-09-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210914_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_EMOTION_IMAGE',
            new_name='UPLOAD_BLOOD_CELL_IMAGE',
        ),
    ]
