# Generated by Django 3.2.5 on 2021-12-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210914_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_BLOOD_CELL_IMAGE',
            new_name='UPLOAD_IMAGE',
        ),
    ]
