# Generated by Django 3.2.5 on 2022-05-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_upload_blood_cell_image_employee_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_IMAGE',
            new_name='UPLOAD_PADDY_LEAF_IMAGE',
        ),
    ]
