# Generated by Django 4.0.4 on 2022-09-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_upload_image_employee_upload_paddy_leaf_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_PADDY_LEAF_IMAGE',
            new_name='UPLOAD_NAIL_IMAGE',
        ),
    ]
