# Generated by Django 4.0.4 on 2022-11-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_upload_paddy_leaf_image_employee_upload_nail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_NAIL_IMAGE',
            new_name='UPLOAD_IMAGE',
        ),
    ]
